added rsync checks

diff --git a/bin/lipsync-setup b/bin/lipsync-setup
--- a/bin/lipsync-setup
+++ b/bin/lipsync-setup
@@ -1,4 +1,17 @@
 #!/bin/bash
+lipsync-prereq-rsync(){
+  type -P rsync &>/dev/null || { echo; echo "	ERROR: lipsync requires rsync but it's not installed" >&2; exit 1; }
+  RSYNC_VERS=$(rsync --version | grep '^rsync *version' | tr -s ' ' | cut -f 3 -d ' ')
+  RSYNC_MAJOR=${RSYNC_VERS%%.*}
+  if [[ ${RSYNC_MAJOR} -lt 3 ]];
+  then
+    echo; echo " ERROR: lipsync requires rsync > 3.0.0 but it's version ${RSYNC_VERS}" >&2;
+    exit 1
+  else
+    return
+  fi
+}
+
 lipsync-prereqs(){
   ########################################
   # Check for required software
@@ -6,8 +19,7 @@ lipsync-prereqs(){
   echo -n "* Checking for required software..."
   type -P ssh &>/dev/null || { echo; echo "	ERROR: lipsync requires ssh-client but it's not installed" >&2; exit 1; }
   type -P ssh-copy-id &>/dev/null || { echo; echo "	ERROR: lipsync requires ssh-copy-id but it's not installed" >&2; exit 1; }
-  #TODO check rsync version both local and remote
-  type -P rsync &>/dev/null || { echo; echo "	ERROR: lipsync requires rsync but it's not installed" >&2; exit 1; }
+  lipsync-prereq-rsync
   type -P lsyncd &>/dev/null || { echo; echo "	ERROR: lipsync requires lsyncd but it's not installed" >&2; exit 1; }
   echo "ok"
 }
